VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "CRegleComblement"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' Classe CRegleComblement
Public NomRegle As String
Public Priorite As Integer
Public ManqueMatinOp As String
Public ManqueMatinVal As Long
Public ManqueAMOp As String
Public ManqueAMVal As Long
Public ManqueSoirOp As String
Public ManqueSoirVal As Long
Public CodesCandidats As Variant
