' ExportedAt: 2026-01-12 15:37:08 | Workbook: Planning_2026.xlsm
VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "CReplacementInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'== Module de classe (Class Module) nommé ReplacementInfo ==
Public sourceLineNum As Long
Public shiftCode As String
Public IsNurse As Boolean
Public IsASBD As Boolean
Public DemandDate As Date
Public IsWeekend As Boolean
Public IsHoliday As Boolean
